import { RefreshCw, Sparkles, Wallet } from "lucide-react";
import { DayTabs } from "./Days";
import { ItineraryItem } from "./ItenaryItem";
import { PopularOptions } from "./PopularOptions";

// --- Sub-Component: Itinerary View ---
 export const ItineraryView = ({ planData, currentDay, setCurrentDay, dummyItinerary, dummyPopularOptions } : any) => {
    const totalDays = planData.days;
    const dayItinerary = dummyItinerary[currentDay] || [];

    // Format budget for display
    let budgetText = planData.budget.charAt(0).toUpperCase() + planData.budget.slice(1);
    if (planData.budget === 'economy') budgetText += ' (Low)';
    else if (planData.budget === 'luxury') budgetText += ' (High)';

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">

            {/* Plan Summary Header */}
            <div className="bg-white p-6 rounded-xl shadow-lg mb-8 border-t-4 border-teal-500">
                <div className="flex flex-col md:flex-row md:justify-between md:items-center">
                    <div className="mb-4 md:mb-0">
                        <h1 className="text-3xl font-bold text-gray-800">{totalDays}-Day Plan for {planData.city}</h1>
                        <p className="text-gray-500">Generated by AI for {planData.city}. Ready to explore!</p>
                    </div>
                    <div className="flex items-center space-x-4">
                        <span className="text-sm font-medium text-gray-700 flex items-center bg-gray-100 p-2 rounded-lg">
                            <Wallet className="w-4 h-4 mr-1 text-green-500" />
                            {budgetText}
                        </span>
                        <span className="text-sm font-medium text-gray-700 flex items-center bg-gray-100 p-2 rounded-lg">
                            <Sparkles className="w-4 h-4 mr-1 text-purple-500" />
                            {planData.style}
                        </span>
                    </div>
                </div>
            </div>

            {/* Main Content Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                
                {/* Left Column: Daily Itinerary & Day Tabs */}
                <div className="lg:col-span-3">
                    <div className="bg-white rounded-xl shadow-lg p-6">
                        
                        <DayTabs 
                            totalDays={totalDays} 
                            currentDay={currentDay} 
                            setCurrentDay={setCurrentDay} 
                        />
                        
                        {/* Itinerary Content for Selected Day */}
                        <div className="space-y-6" id="itinerary-content">
                            {dayItinerary.length === 0 ? (
                                <div className="p-6 bg-gray-50 rounded-lg text-center text-gray-500">
                                    <RefreshCw className="w-6 h-6 mx-auto mb-2 text-teal-400" />
                                    <p>No detailed itinerary found for Day {currentDay}.</p>
                                    <p className="text-xs mt-2">Try regenerating the plan or manually adding activities.</p>
                                </div>
                            ) : (
                                dayItinerary.map((item: any, index: number) => (
                                    <ItineraryItem key={index} item={item} />
                                ))
                            )}
                        </div>
                    </div>
                </div>

                {/* Right Column: Popular Options (Now using the dedicated component) */}
                <div className="lg:col-span-1">
                    <PopularOptions 
                        currentDay={currentDay} 
                        dummyPopularOptions={dummyPopularOptions} 
                    />
                </div>
            </div>
        </div>
    );
};
